import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowRight, Shield, Zap, Globe, CheckCircle, TrendingUp, Lock } from 'lucide-react';
import { Button } from '../components/ui/Button';
import { Card } from '../components/ui/Card';

export default function Landing() {
  const features = [
    {
      icon: Zap,
      title: 'Instant Payments',
      description: 'Pay with crypto, receive local currency instantly. No waiting, no delays.',
      color: 'bg-gray-900',
    },
    {
      icon: Shield,
      title: 'Secure & Trusted',
      description: 'Built on Stellar blockchain. Your transactions are safe and transparent.',
      color: 'bg-gray-800',
    },
    {
      icon: Globe,
      title: 'Global Reach',
      description: 'Accept payments from anywhere in the world. No borders, no limits.',
      color: 'bg-gray-900',
    },
    {
      icon: CheckCircle,
      title: 'Easy Integration',
      description: 'Simple QR code system. Works perfectly for any modern business.',
      color: 'bg-gray-800',
    },
  ];

  const steps = [
    { number: '1', title: 'Connect Wallet', description: 'Link your Stellar wallet (Freighter) securely.' },
    { number: '2', title: 'Scan QR Code', description: 'Scan the payment QR code generated by the merchant.' },
    { number: '3', title: 'Confirm', description: 'Review the amount and confirm your transaction.' },
    { number: '4', title: 'Done!', description: 'Merchant receives funds instantly.' },
  ];

  const stats = [
    { label: 'Transactions', value: '10M+', icon: TrendingUp },
    { label: 'Active Users', value: '50K+', icon: Globe },
    { label: 'Merchants', value: '5K+', icon: CheckCircle },
    { label: 'Uptime', value: '99.9%', icon: Lock },
  ];

  return (
    <div className="min-h-screen bg-background">
      {/* Hero Section */}
      <section className="relative overflow-hidden pt-32 pb-24 md:pt-40 md:pb-36 px-4 bg-[#fcfcfd]">

        {/* Premium Background */}
        <div className="absolute inset-0">
          <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[800px] h-[800px] bg-gradient-to-br from-gray-200/40 via-gray-100/20 to-transparent rounded-full blur-3xl"></div>

          <div className="absolute top-20 left-10 w-72 h-72 bg-blue-100/30 rounded-full blur-3xl"></div>

          <div className="absolute bottom-0 right-0 w-96 h-96 bg-indigo-100/30 rounded-full blur-3xl"></div>

          <div className="absolute inset-0 bg-[linear-gradient(to_right,#f3f4f610_1px,transparent_1px),linear-gradient(to_bottom,#f3f4f610_1px,transparent_1px)] bg-[size:64px_64px]"></div>
        </div>

        <div className="container mx-auto max-w-7xl relative z-10">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7 }}
            className="text-center"
          >

            {/* Top Badge */}
            <motion.div
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.5 }}
              className="inline-flex items-center gap-3 px-5 py-2.5 rounded-full border border-white/70 bg-white/70 backdrop-blur-2xl shadow-xl mb-10"
            >
              <div className="relative flex items-center justify-center">
                <span className="absolute w-3 h-3 bg-emerald-400 rounded-full animate-ping"></span>
                <span className="relative w-3 h-3 bg-emerald-500 rounded-full"></span>
              </div>

              <span className="text-sm font-semibold tracking-wide text-gray-800">
                Powered by Stellar Blockchain
              </span>
            </motion.div>

            {/* Heading */}
            <motion.div
              initial={{ opacity: 0, y: 25 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.7, delay: 0.1 }}
            >
              <h1 className="text-5xl sm:text-6xl md:text-7xl lg:text-[92px] font-black tracking-[-0.05em] leading-[0.95] text-gray-950">
                The Future of
                <br />

                <span className="relative inline-block">
                  <span className="bg-gradient-to-r from-gray-900 via-gray-700 to-gray-500 bg-clip-text text-transparent">
                    Crypto Payments
                  </span>

                  <div className="absolute -bottom-3 left-0 w-full h-6 bg-gradient-to-r from-gray-200/60 to-gray-100/10 blur-2xl"></div>
                </span>
              </h1>
            </motion.div>

            {/* Subtitle */}
            <motion.p
              initial={{ opacity: 0, y: 25 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.7, delay: 0.25 }}
              className="mt-8 text-lg sm:text-xl md:text-2xl text-gray-500 max-w-3xl mx-auto leading-relaxed font-normal"
            >
              Seamlessly accept crypto payments with
              <span className="font-semibold text-gray-800"> XLM </span>
              and
              <span className="font-semibold text-gray-800"> USDC </span>
              while merchants instantly receive local currency through StellarPay’s ultra-fast infrastructure.
            </motion.p>

            {/* CTA Buttons */}
            <motion.div
              initial={{ opacity: 0, y: 25 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.7, delay: 0.4 }}
              className="mt-12 flex  items-center justify-center gap-5"
            >

              <Link to="/auth">
                <Button
                  size="lg"
                  className="
              group
              relative
              overflow-hidden
              rounded-2xl
              px-6
              py-4
              text-base
              font-semibold
              bg-gray-950
              hover:bg-black
              text-white
              shadow-[0_20px_60px_rgba(0,0,0,0.18)]
              hover:shadow-[0_25px_70px_rgba(0,0,0,0.22)]
              transition-all
              duration-300
              hover:-translate-y-1
            "
                >
                  <span className="relative z-10 flex items-center gap-2">
                    Get Started
                    <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform duration-300" />
                  </span>

                  <div className="absolute inset-0 bg-gradient-to-r from-white/10 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
                </Button>
              </Link>

              <Link to="/auth">
                <Button
                  variant="outline"
                  size="lg"
                  className="
              rounded-2xl
               px-6
              py-4
              text-base
              font-semibold
              border
              border-gray-200
              bg-white/80
              backdrop-blur-xl
              hover:bg-white
              hover:border-gray-300
              text-gray-900
              shadow-lg
              hover:shadow-xl
              transition-all
              duration-300
              hover:-translate-y-1
            "
                >
                  Sign In
                </Button>
              </Link>
            </motion.div>

            {/* Bottom Stats */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.6 }}
              className="mt-20 grid grid-cols-1 sm:grid-cols-3 gap-5 max-w-4xl mx-auto"
            >

              {[
                ["⚡", "Instant Settlement"],
                ["🔒", "Secure Stellar Network"],
                ["🌍", "Global Crypto Payments"],
              ].map(([icon, text], index) => (
                <div
                  key={index}
                  className="
              rounded-3xl
              border
              border-white/60
              bg-white/60
              backdrop-blur-2xl
              px-6
              py-5
              shadow-lg
              hover:shadow-xl
              transition-all
              duration-300
              hover:-translate-y-1
            "
                >
                  <div className="text-2xl mb-2">{icon}</div>

                  <p className="text-sm font-medium text-gray-700">
                    {text}
                  </p>
                </div>
              ))}
            </motion.div>
          </motion.div>
        </div>
      </section>

      {/* Stats Section */}
      <section className="py-16 px-4 bg-white border-y border-gray-100">
        <div className="container mx-auto max-w-6xl">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
            {stats.map((stat, index) => {
              const Icon = stat.icon;
              return (
                <motion.div
                  key={stat.label}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: index * 0.1 }}
                  className="text-center"
                >
                  <div className="w-12 h-12 rounded-xl bg-gray-50 flex items-center justify-center mx-auto mb-4 border border-gray-100 shadow-sm">
                    <Icon className="w-5 h-5 text-gray-900" />
                  </div>
                  <p className="text-3xl font-bold text-gray-900 mb-1">{stat.value}</p>
                  <p className="text-sm text-gray-500 font-medium">{stat.label}</p>
                </motion.div>
              );
            })}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-24 px-4 bg-background">
        <div className="container mx-auto max-w-6xl">
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <h2 className="text-4xl md:text-5xl font-bold mb-4 text-gray-900 tracking-tight">How It Works</h2>
            <p className="text-lg text-gray-500">
              Simple, fast, and remarkably secure.
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {steps.map((step, index) => (
              <motion.div
                key={step.number}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.1 }}
              >
                <Card className="text-center h-full border-gray-100 shadow-premium hover:shadow-premium-hover transition-all duration-300 bg-white/60 backdrop-blur-sm">
                  <div className="w-14 h-14 rounded-2xl bg-gray-900 flex items-center justify-center text-white text-xl font-bold mx-auto mb-6 shadow-md">
                    {step.number}
                  </div>
                  <h3 className="text-xl font-semibold mb-2 text-gray-900">
                    {step.title}
                  </h3>
                  <p className="text-gray-500 leading-relaxed text-sm">
                    {step.description}
                  </p>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="py-24 px-4 bg-white border-t border-gray-100">
        <div className="container mx-auto max-w-6xl">
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <h2 className="text-4xl md:text-5xl font-bold mb-4 text-gray-900 tracking-tight">Why StellarPay?</h2>
            <p className="text-lg text-gray-500">
              Built for the modern financial stack.
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {features.map((feature, index) => {
              const Icon = feature.icon;
              return (
                <motion.div
                  key={feature.title}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: index * 0.1 }}
                >
                  <Card className="h-full border-gray-100 shadow-premium hover:shadow-premium-hover transition-all duration-300">
                    <div className={`w-12 h-12 rounded-xl ${feature.color} flex items-center justify-center mb-6 shadow-md`}>
                      <Icon className="w-5 h-5 text-white" />
                    </div>
                    <h3 className="text-xl font-semibold mb-3 text-gray-900">
                      {feature.title}
                    </h3>
                    <p className="text-gray-500 leading-relaxed text-sm">
                      {feature.description}
                    </p>
                  </Card>
                </motion.div>
              );
            })}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-24 px-4 bg-gray-900 text-white relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-b from-transparent to-gray-950/50" />
        <div className="container mx-auto max-w-4xl text-center relative z-10">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
          >
            <h2 className="text-4xl md:text-5xl font-bold mb-6 tracking-tight">
              Ready to Get Started?
            </h2>
            <p className="text-xl text-gray-400 mb-10 leading-relaxed max-w-2xl mx-auto">
              Join the future of payments. Fast, remarkably secure, and borderless.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link to="/auth">
                <Button size="lg" className="bg-white text-gray-900 hover:bg-gray-100 px-8 py-6 rounded-2xl shadow-premium text-base">
                  Create Account
                </Button>
              </Link>
            </div>
          </motion.div>
        </div>
      </section>
    </div>
  );
}
